### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by asdt560** [d4nQw3rty/Ruby-group-capstone---Catalog-of-my-things#26]
[Ruby Capstone Project](https://github.com/users/d4nQw3rty/projects/2/views/1). There are 3 people in this team:

- Team Member 1: [asdt560](https://github.com/asdt560)
- Team Member 2: [Kelvin-Ben](https://github.com/Kelvin-Ben)
- Team Member 3: [d4nQw3rty](https://github.com/d4nQw3rty)

**Comment by OLIPLICHE** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Created the Kanban board👏 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
